"""
Shortest Path Finding in a Maze - Streamlit Application
UI Layout Matching Wireframe Diagram
Live BFS Execution & Real-Time Metrics
Dual Algorithm Support (BFS & Dijkstra)
Tri-Algorithm Support (BFS, Dijkstra, A*)
Complete 4-Algorithm BFS,Dijkstra,A*,Bellmann_Ford
Multi-Algorithm Benchmarking Engine & Comparative Dashboard
"""
import streamlit as st
import pandas as pd
from maze.maze import Maze
from algorithms.bfs import solve_bfs
from algorithms.dijkstra import solve_dijkstra
from algorithms.astar import solve_astar
from algorithms.bellman_ford import solve_bellman_ford
from visualization.plotter import plot_maze

st.set_page_config(
    page_title="Maze Shortest-Path Visualizer",
    page_icon="🧩",
    layout="wide"
)

def main():
    st.title("Maze Shortest-Path Visualizer")
    st.caption("localhost:8501 — Comparative Pathfinding Engine")
    st.divider()

    col_controls, col_maze, col_metrics = st.columns([1, 2, 1])

    # --- PANEL 1: CONTROLS ---
    with col_controls:
        st.subheader("CONTROLS")
        maze_size = st.selectbox("Maze Size", ["11x11", "21x21", "31x31"], index=0, key="sb_maze_size")
        size = int(maze_size.split("x")[0])

        st.write("**Select Algorithms to Compare:**")
        use_bfs = st.checkbox("BFS", value=True, key="chk_bfs")
        use_dijkstra = st.checkbox("Dijkstra's", value=True, key="chk_dijkstra")
        use_astar = st.checkbox("A*", value=True, key="chk_astar")
        use_bellman = st.checkbox("Bellman-Ford", value=True, key="chk_bellman")

        st.write("")
        btn_generate = st.button("🎲 Generate Classic Maze", use_container_width=True, key="btn_gen")
        btn_run = st.button("▶ Run Comparison", type="primary", use_container_width=True, key="btn_run")

    # Initialize or update maze instance when size changes
    if "maze" not in st.session_state or st.session_state.maze.rows != size:
        st.session_state.maze = Maze(rows=size, cols=size)

    maze = st.session_state.maze

    # Handle Classic Maze Generation trigger
    if btn_generate:
        maze.generate_random_maze()
        st.rerun()

    # Execute selected search algorithms concurrently
    benchmark_data = []
    if btn_run:
        if use_bfs:
            benchmark_data.append(solve_bfs(maze))
        if use_dijkstra:
            benchmark_data.append(solve_dijkstra(maze))
        if use_astar:
            benchmark_data.append(solve_astar(maze))
        if use_bellman:
            benchmark_data.append(solve_bellman_ford(maze))

    # --- PANEL 2: MAZE VIEW ---
    with col_maze:
        st.subheader("MAZE VIEW")
        st.info(f"Grid Canvas: {maze.rows} × {maze.cols}")
        st.write(f"**Start:** `{maze.start}` | **End:** `{maze.end}`")

        # Extract path from the fastest execution
        optimal_path = None
        if benchmark_data:
            fastest_run = min(benchmark_data, key=lambda x: x["execution_time_ms"])
            optimal_path = fastest_run["path"]
            st.success(f"Path calculated! Showing route generated by {fastest_run['algorithm']}.")

        # Render 2D Grid Canvas
        fig = plot_maze(maze, path=optimal_path)
        st.pyplot(fig, use_container_width=True)

    # --- PANEL 3: BENCHMARKS ---
    with col_metrics:
        st.subheader("BENCHMARKS")
        if benchmark_data:
            df = pd.DataFrame(benchmark_data)
            table_df = df[["algorithm", "path_length", "nodes_explored", "execution_time_ms", "space_used"]].copy()
            table_df.columns = ["Algorithm", "Path Cost", "Nodes Explored", "Time (ms)", "Peak Space"]

            st.dataframe(table_df, use_container_width=True, hide_index=True)

            best_nodes = min(benchmark_data, key=lambda x: x["nodes_explored"])
            st.caption(f"🏆 **Most Efficient:** `{best_nodes['algorithm']}` explored the fewest cells ({best_nodes['nodes_explored']}).")
        else:
            st.write("Click **▶ Run Comparison** to evaluate metrics.")

if __name__ == "__main__":
    main()